# Generated by Django 5.2.17 on 2026-09-27 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nacionalidade', models.CharField(blank=True, max_length=80)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('ano_publicacao', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('FICCAO', 'Ficção'), ('ROMANCE', 'Romance'), ('TECNICO', 'Técnico'), ('BIOGRAFIA', 'Biografia'), ('FANTASIA', 'Fantasia')], max_length=30)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='biblioteca.autor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
